#!/bin/bash

# GitHub Pages Setup Script
# This script provides instructions for enabling GitHub Pages

echo "🚀 GitHub Pages Setup Instructions"
echo "=================================="
echo ""
echo "Your gh-pages branch has been created and pushed to GitHub!"
echo ""
echo "Next steps to enable GitHub Pages:"
echo ""
echo "1. Go to your repository on GitHub:"
echo "   https://github.com/NewAlexandria/undersea-cable"
echo ""
echo "2. Click on 'Settings' tab"
echo ""
echo "3. Scroll down to 'Pages' in the left sidebar"
echo ""
echo "4. Under 'Source', select 'Deploy from a branch'"
echo ""
echo "5. Choose 'gh-pages' branch and '/ (root)' folder"
echo ""
echo "6. Click 'Save'"
echo ""
echo "7. Wait 5-10 minutes for GitHub to build your site"
echo ""
echo "8. Your microsite will be available at:"
echo "   https://newalexandria.github.io/undersea-cable/"
echo ""
echo "📋 What's included in your microsite:"
echo "• Complete business documentation"
echo "• Technical architecture guides"
echo "• Analysis results and visualizations"
echo "• Responsive design with navigation"
echo "• SEO optimization"
echo ""
echo "📁 Site structure:"
echo "• Homepage with overview and navigation"
echo "• Executive summary and business strategy"
echo "• Technical architecture documentation"
echo "• Complete analysis section with results"
echo "• Visualizations and data files"
echo ""
echo "🎨 Customization:"
echo "• Edit assets/css/style.css for styling"
echo "• Update _config.yml for site configuration"
echo "• Add new pages by creating .md files with front matter"
echo ""
echo "✅ Setup complete! Follow the steps above to enable GitHub Pages."
